### ISSUE TITLE
error TS2456: Type alias 'ParserStateResult' circularly references itself.

### ISSUE THREAD

**Issue by Bikossor** [Bikossor/Railgun#42]
With TypeScript version `3.4.5`.

**Comment by Bikossor** [comment]
I don't know when this got added to TypeScript but it works with the version `4.1.3`.
